# Generated by Django 2.1.7 on 2019-08-16 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0007_auto_20190816_1751'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.FloatField(max_length=30)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_exam', to='analysis.Examinations')),
            ],
        ),
        migrations.CreateModel(
            name='GameEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bronze_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_entries_bronze', to='analysis.Questions')),
                ('golden_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_entries_golden', to='analysis.Questions')),
                ('questions', models.ManyToManyField(blank=True, related_name='game_entries_question', to='analysis.Questions')),
                ('silver_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_entries_silver', to='analysis.Questions')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_entries_subject', to='analysis.Subjects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_entries_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entries', models.ManyToManyField(blank=True, to='Game.GameEntries')),
                ('game_for_exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_game', to='analysis.Examinations')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_subjects_subject', to='analysis.Subjects')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_subjects',
            field=models.ManyToManyField(blank=True, to='Game.GameSubjects'),
        ),
        migrations.AddField(
            model_name='game',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_semester', to='analysis.Semesters'),
        ),
    ]
