# Generated by Django 2.1.7 on 2019-08-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(default=0, max_length=30),
        ),
    ]
