# Generated by Django 2.2.3 on 2019-08-05 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.FloatField(max_length=30)),
                ('unique_id', models.CharField(default=uuid.uuid4, max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('modules', models.ManyToManyField(to='analysis.Modules')),
            ],
        ),
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subjects', models.ManyToManyField(to='analysis.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('difficulty_level', models.CharField(max_length=20)),
                ('times_asked', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('weight', models.FloatField(max_length=30)),
                ('number_of_imp_by_user', models.IntegerField()),
                ('percent_imp', models.IntegerField()),
                ('probability_of_ask', models.IntegerField()),
                ('unique_id', models.CharField(default=uuid.uuid4, max_length=500, unique=True)),
                ('examinations', models.ManyToManyField(to='analysis.Examinations')),
                ('imp_by_users', models.ManyToManyField(related_name='imp_by_useruser', to=settings.AUTH_USER_MODEL)),
                ('question_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.Examinations')),
                ('questions', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='modules',
            name='questions',
            field=models.ManyToManyField(to='analysis.Questions'),
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('semesters', models.ManyToManyField(to='analysis.Semesters')),
            ],
        ),
    ]
