# Generated by Django 2.1.7 on 2019-08-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='examinations',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='imp_by_users',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='number_of_imp_by_user',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='percent_imp',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='probability_of_ask',
        ),
        migrations.AlterField(
            model_name='questions',
            name='times_asked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='weight',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
    ]
