# Generated by Django 2.1.7 on 2019-08-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20190815_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='times_asked',
        ),
    ]
