# Generated by Django 2.1.7 on 2019-08-16 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0006_auto_20190816_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.FloatField(max_length=30)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.Examinations')),
            ],
        ),
        migrations.CreateModel(
            name='GameEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golden_question', models.CharField(max_length=50)),
                ('silver_question', models.CharField(max_length=50)),
                ('bronze_question', models.CharField(max_length=50)),
                ('questions', models.ManyToManyField(blank=True, to='analysis.Questions')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.Subjects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entries', models.ManyToManyField(blank=True, to='analysis.GameEntries')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.Subjects')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_subjects',
            field=models.ManyToManyField(blank=True, to='analysis.GameSubjects'),
        ),
        migrations.AddField(
            model_name='game',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.Semesters'),
        ),
    ]
