# Generated by Django 2.1.7 on 2019-08-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20190816_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_subjects',
        ),
        migrations.RemoveField(
            model_name='game',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='gameentries',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='gameentries',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='gameentries',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gamesubjects',
            name='entries',
        ),
        migrations.RemoveField(
            model_name='gamesubjects',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameEntries',
        ),
        migrations.DeleteModel(
            name='GameSubjects',
        ),
    ]
