# Generated by Django 2.1.7 on 2019-08-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20190816_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='unique_id',
        ),
    ]
